### ISSUE TITLE
can only run as pid 1

### ISSUE THREAD

**Issue by kohlsalem** [loganmarchione/hassos-addons#2]
Hi,

i try to run the addon on my ODroid-N2 running  

Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.1
Home Assistant OS 7.6
Kernel version 5.10.108
Agent version 1.2.1

I did disable protection mode, however, starting the Addon i just end up with

`s6-overlay-suexec: fatal: can only run as pid 1.`

as sole entry in the log.

Anything i can do about this?

Thanks
Michael

**Comment by loganmarchione** [comment]
Interesting. Mine was working fine, and I even restarted the add-on and it was still working. However, when I uninstalled it and reinstalled it, I'm getting the same error as you.

`s6-overlay-suexec: fatal: can only run as pid 1`

Nothing has changed in my repo, so it must be something Home Assistant changed. I'll have to look into this...

**Comment by loganmarchione** [comment]
Ah ok, it has something to do with this. Apparently it just changed yesterday. Looking into this now.

https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images

**Comment by kohlsalem** [comment]
So its fair to say that i had a bad timing with my monitoring tinkerings :-)

Thanks for looking after it!

**Comment by nathang21** [comment]
Happening to me as well, only triggered after i restored my env from a backup which reinstalled the .

Happy to provide any logs or details that can be helpful if requested..

**Comment by loganmarchione** [comment]
I've tried setting `"init": false` in the config.json and making my scripts executable per the blog post, but am having no luck. I've posted twice on the Home Assistant developer forums, so we'll see what comes of that 🤷🏻‍♂️ My only other option would be to use Alpine 3.11 as a base (which did not receive the S6 update), but that went out of support in 2021 I believe...

**Comment by kohlsalem** [comment]
Works nicely, thanks!
