### ISSUE TITLE
How can I determine which version of node_exporter is running?

### ISSUE THREAD

**Issue by james-millner** [loganmarchione/hassos-addons#38]
Sorry folks, more of a question than an issue. But I'm trying to pinpoint what version of node_exporter this addon runs?

**Comment by loganmarchione** [comment]
We're on 1.5.0 as per this line. 

https://github.com/loganmarchione/hassos-addons/blob/main/prometheus_node_exporter/Dockerfile#L11

**Comment by james-millner** [comment]
Nice thanks @loganmarchione, any hesitation to go to 1.6.1 the most recent release? I'm not aware of any breaking changes though between 1.5 & 1.6 though. Can this be community raised?

**Comment by loganmarchione** [comment]
No problem there, just didn't know it was out (I don't update this container often). I can get that done in a few mins here.

**Comment by loganmarchione** [comment]
I just pushed `0.7.0` with node exporter `1.6.1`. You'll have to check for updates in HA to see it.
